### ISSUE TITLE
Getting missing file app.js

### ISSUE THREAD

**Issue by bradenpowers** [appcelerator/titanium#115]
Hi,

What is happening is that I had a app that was working fine.  I deleted it from my sim. Then I tried to reload the app and I got this error:

[ERROR] Error loading path: file:///Users/bradenpowers/Library/Application%20Support/iPhone%20Simulator/7.0.3/Applications/627F3E26-8B17-470F-B675-3703ADA87843/Citadel%20Mobile.app/app.js, Error Domain=NSCocoaErrorDomain Code=260 "The operation couldn’t be completed. (Cocoa error 260.)" UserInfo=0xd068210 {NSFilePath=/Users/bradenpowers/Library/Application Support/iPhone Simulator/7.0.3/Applications/627F3E26-8B17-470F-B675-3703ADA87843/Citadel Mobile.app/app.js, NSUnderlyingError=0xd0681b0 "The operation couldn’t be completed. No such file or directory"}
[ERROR] Script Error Could not find the file app.js

I get the same error using the CLI or Studio.  It is an Alloy project.

**Comment by fabrizio5680** [comment]
Having same issue

**Comment by cb1kenobi** [comment]
I've seen this before a long time ago, but I believe it's been fixed. Could you please file a ticket in https://jira.appcelerator.org and include as much detail as you can: Titanium CLI version (run "ti -v"), Titanium SDK version (in tiapp.xml), output from "ti config", Alloy version (run "alloy -v"), etc. Someone will be able to help you.

**Comment by bradenpowers** [comment]
yeah...sorry. It was fixed with a reload of titanium and alloy.

**Comment by cb1kenobi** [comment]
Cool, closing ticket. :)
