### ISSUE TITLE
Name file for NDK android

### ISSUE THREAD

**Issue by alejonext** [appcelerator/titanium#185]
the new NDK for android the name the file is in uppercase the extnsion.

**Comment by skypanther** [comment]
I'm sorry, I'm not understanding what you're saying. 

A. The new Android NDK from Google contains a file that has an uppercase extension (which is causing issues with the Titanium tooling)?
B. Something in Titanium has changed and is now looking for an NDK file with an uppercase extension when it should be looking for a lowercase extension?

I downloaded and extracted OS X Android NDK r10d (newest available today) and don't see an issue with uppercase extensions. So, I suspect you mean option B. Can you please point me to a specific file or error message so I can investigate this further?

**Comment by alejonext** [comment]
The filename, which is tested to see if there NDK in particular folder. Change from new the new NDK, and is a bad practice test it with a file called `RELEASE.txt`. When should I be tested, the file `ndk-build`. Well... i use ubuntu.
