### ISSUE TITLE
Titanium Create New App with Cloud-Enable option

### ISSUE THREAD

**Issue by harryjin** [appcelerator/titanium#209]
Hey Guys,
I'm happy to use Titanium CLI.
But i don't find the way to create new app with cloud-enable option(ACS).
Please let me know how to create new app with cloud-enable option by cli.
Thanks.

**Comment by ingo** [comment]
You will want to use the new platform and "appc new" (npm -g install appcelerator). This option is not available in the Titanium CLI.

**Comment by harryjin** [comment]
Thanks for your message.
I tried to use appc new command.
But i got following message.
ERROR  | You don't have access to Appcelerator Platform yet. Please contact your administrator to get access.
How can i continue to work it?

**Comment by ingo** [comment]
You need to sign up at appcelerator.com and wait for the invite.
