### ISSUE TITLE
Studio: Error connecting to download server Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by Priler** [appcelerator/titanium#236]
Hi!

I'm running Appcelerator Studio x64 for Linux under Ubuntu 14.04 LTS.

And i'm already ran this commands below.
```
sudo apt-get install libjpeg62 libwebkitgtk-1.0-0
echo 'export MOZILLA_FIVE_HOME=/usr/lib/mozilla' >> ~/.bashrc
```
And,  i do have ACS, Alloy, Titanium CLI and other stuff installed via NPM.
And, i do have Oracle-Java-7 installed.
And, i already ran this command "appc setup"

But still i having this error: http://imgur.com/5fOryax

If it helps, i followed this instruction: http://tutorialforlinux.com/2014/04/19/how-to-install-appcelerator-titanium-studio-on-ubuntu-14-04-trusty-lts-64bit-linux-step-by-step/
Is there a way to launch Appcelerator Studio in Ubuntu 14.04 LTS?

Versions of installed stuff:
```
NodeJS: v0.12.7
Alloy: 1.7.29
Acs: 1.0.32
Titanium CLI: 5.0.5
Titanium SDK: 4.0.0.GA [selected]  4.0.0.v20150518154210 /home/abraham/.titanium/mobilesdk/linux/4.0.0.GA
```

p.s. running this from terminal not helping (even Login button not works).

**Comment by cb1kenobi** [comment]
Hi @Priler, this project is for the Titanium CLI. You will need to file your issue in https://jira.appcelerator.org/ so that the Appcelerator Studio can handle your issue. Thank you!
