### ISSUE TITLE
Building for submission to app store fails

### ISSUE THREAD

**Issue by southworthk** [appcelerator/titanium#238]
Running the command to package the application for app store submission results in an error. 

    ti build -p ios -T dist-appstore -R "<Company Name>" -P "<Distribution Certificate>"

    [ERROR] :  titanium_prep failed to run (10)
    [ERROR] :  This application cannot be built with the Titanium open source SDK because it is an Appcelerator Platform registered application. Please use the Appcelerator Platform CLI tools or Appcelerator Studio to build this application.

I've unregistered the application with Appcelerator and have tried using the SDK's greater than 4.X.X, all with the same result.

**Comment by cb1kenobi** [comment]
You need to use `appc run`, not `ti build`. The rest of the command line arguments are the same.
