### ISSUE TITLE
Toolchain silently ignores invalid quotes in tiapp.xml

### ISSUE THREAD

**Issue by Bostwickenator** [appcelerator/titanium#244]
When adding modules the toolchain will happily process the following:
`<module platform=“iphone” version="1.0.0">com.example.test</module>`
silently and then cause run-time module lookup failures.

Change it to:
`<module platform="iphone" version="1.0.0">com.example.test</module>`
and everything works correctly

**Comment by cb1kenobi** [comment]
Smart quotes are not valid in XML. I wonder what the XML parser library is doing. I wouldn't be surprised if the platform was being parsed as `"“iphone”"`. I don't think we should naively replace all smart quotes with ascii quotes and properly scrubbing the smart quotes is more effort than it's worth. In other words, I don't think we're going to improve this.
