### ISSUE TITLE
Path must be a string. Received undefined  

### ISSUE THREAD

**Issue by mahendrapatel** [appcelerator/titanium#248]
i run a simple hello world program which run in browser perfectly but when 
deploying in android mobile it case the following error 
...
...
[INFO] :   Packaging application: /home/ankit/Android/Sdk/build-tools/24.0.0/aapt "package" "-f" "-m" "-J" "/home/ankit/Appcelerator_Studio_Workspace/Hello/build/android/gen" "-M" "/home/ankit/Appcelerator_Studio_Workspace/Hello/build/android/AndroidManifest.xml" "-A" "/home/ankit/Appcelerator_Studio_Workspace/Hello/build/android/bin/assets" "-S" "/home/ankit/Appcelerator_Studio_Workspace/Hello/build/android/res" "-I" "/home/ankit/Android/Sdk/platforms/android-23/android.jar" "-F" "/home/ankit/Appcelerator_Studio_Workspace/Hello/build/android/bin/app.ap_" "--auto-add-overlay" "--extra-packages" "ti.modules.titanium.ui:android.support.v7.appcompat:android.support.v7.cardview" "-S" "/tmp/116611-26251-glfet8.13w744pldi/res" "-S" "/tmp/116611-26251-2govyk.i30ytoi529/res" "-S" "/tmp/116611-26251-1coto6l.3oour9hpvi/res"
2016-07-11T11:10:27.847Z | ERROR  | An uncaught exception was thrown!
Path must be a string. Received undefined
2016-07-11T11:10:27.848Z | ERROR  | Path must be a string. Received undefined

**Comment by ashcoding** [comment]
How are you compiling the code via?

**Comment by cb1kenobi** [comment]
We are tracking this issue in our official bug tracking system. Please follow progress here: https://jira.appcelerator.org/browse/CLI-1056.

**Comment by bahinapster** [comment]
Hello , 

i just removed node and reinstall it , works fine now.

**Comment by Mashqur** [comment]
I have one project which is running but the new one is not running. Facing this error. If node version is the cause then older app should not run right? I am getting confused. Because in my machine node version is 6.X.X

**Comment by cb1kenobi** [comment]
@Mashqur It's definitely not the Node.js version that's the problem. In Node.js, if you do `path.join(something, 'foo')` and `something` is null, undefined, or an empty string, it'll throw that error. I have no idea exactly which `path.join()` call is the culprit. There are hundreds of `path.join()` calls.

The first thing I would do is look at both your Appc CLI and Titanium CLI config files and see if there are any settings that look like paths that are undefined, null, or empty and fixing them. You can find them at `~/.appcelerator/appc-cli.json` and `~/.titanium/config.json`.

**Comment by ewanharris** [comment]
Hey @Mashqur! So this happens because of some changes in Node.js that affect 5.5.1.GA. If your app needs to stay on SDK 5.5.1.GA try to downgrade your Node version to a 4.X version, otherwise upgrading to SDK 6.0.1.GA should fix the issue.
