### ISSUE TITLE
Http response doesn't work for iOS just for Android

### ISSUE THREAD

**Issue by pedrotnascimento** [appcelerator/titanium#256]
Hello,
I have an issue.
I have this code :

xhr = Ti.Network.createHTTPClient();
	xhr.setRequestHeader('Content-Type', 'application/json');
	xhr.open('POST', 'http://adress/to/my/Valid/RESTapi/');
	xhr.onload = function(){
		alert("response " + this.responseText + " "+ JSON.stringify(this);
	};
	xhr.onerror = function(){
		alert("error ss" + this.responseText);
	};
	var sending = [];
	sending.push(SSObject(20021, 2));//returns json struct
	xhr.send(JSON.stringify(sending));//send array with struct

In Android it response correctly, but in iOS I receive a empty array in 'this.responseText' and 'this'  response just {url:'http://adress/to/my/Valid/RESTapi/' ,method: 'POST'}

**Comment by cb1kenobi** [comment]
Hi @pedrotnascimento, thanks for reporting the issue, however this is the wrong issue tracker. Please file a ticket at https://jira.appcelerator.org.
