### ISSUE TITLE
How to make a backwards-compatible Titanium module?

### ISSUE THREAD

**Issue by afjoseph** [appcelerator/titanium#270]
Title says it all: is it possible to make Titanium modules that are backwards-compatible with Titanium apps that are lower than 7.0.0GA?

I tried to set the minsdk value in manifest for my module to 6.0.4GA but Appcelerator doesn't allow me to add it for apps lower than 7.0.0GA.

How can I make a backwards-compatible Titanium module built with Titanium 7.0.0GA?

**Comment by Topener** [comment]
quite an old issue here I see, also this project is the Titanium CLI. To answer your question, you cannot make a backwards compatible module, you'll need to compile 2 versions. That said, this question would've gone well on the Slack community https://tislack.org, not here :) Closing it now.
