### ISSUE TITLE
while doing ti setup command android sdk path is not found

### ISSUE THREAD

**Issue by aviboy2006** [appcelerator/titanium#358]
CLI version 5.2.2, Titanium SDK version 9.0.0.GA
Android studio version : 3.6.1
Titanium Appc version : 9.0.0.GA

While trying to setup titanium using below command : 

`ti setup`

for -a  android setting.

getting below error : 

`: /Users/LaptopUsr/Library/Android/sdk
    [ERROR] Invalid Android SDK path
 Required file does not exist: "/Users/LaptopUsr/Library/Android/sdk/tools/android"
`
i checked in my android folder there is no such folder exist on given location 

list of folder available : 

>build-tools
>emulator
>extras
>licenses	
>ndk		
>patcher		
>platform-tools	
>platforms	
>sources

What should to solve this issue ? is there titanium support upto specific version of above all ? android studio , Appc  etc

**Comment by m1ga** [comment]
try this please: https://github.com/m1ga/from_zero_to_app/blob/master/installation.md#android-studio

**Comment by aviboy2006** [comment]
Thanks this works well.
