### ISSUE TITLE
Error thrown during Alloy compile fails compilation

### ISSUE THREAD

**Issue by chrisdrewry** [appcelerator/titanium#520]
I'm in the process of migrating a project from the Appc CLI to the Titanium CLI ahead of the March 1 end-of-support deadline, and am running into the following during compilation, where `<project-dir>` is my project's root directory with `tiapp.xml`.

The same project compiles successfully with Appc CLI 9.0.1.

```
[INFO]  Executing Alloy compile: <user-dir>/.nvm/versions/node/v12.22.1/bin/node  compile <project-dir>/app --config platform=ios,version=0,simtype=none,devicefamily=universal,deploytype=development,target=simulator
[DEBUG] internal/modules/cjs/loader.js:818
[DEBUG]   throw err;
[DEBUG]   ^
[ERROR] : Cannot find module '<project-dir>/undefined'
[DEBUG]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
[DEBUG]     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
[DEBUG]     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
[DEBUG]     at internal/main/run_main_module.js:17:47 {
[DEBUG]   code: 'MODULE_NOT_FOUND',
[DEBUG]   requireStack: []
[DEBUG] } 
[ERROR] Alloy compiler failed
```

Ti SDK 9.3.2.GA
Titanium CLI 5.4.0
Node v12.22.1

**Comment by ewanharris** [comment]
@chrisdrewry Apologies for that less than helpful error message, I believe you're missing the Alloy CLI. You can install it using `[sudo] npm i alloy -g`

**Comment by chrisdrewry** [comment]
@ewanharris that did the trick! Thank you 😁
