### ISSUE TITLE
High and medium security vulnerabilities in Titanium packages

### ISSUE THREAD

**Issue by brentonhouse** [appcelerator/titanium#533]
There seems to be some high and medium level security vulnerabilities in this and other Titanium packages due to the use of `danger` and `xmldom`.  It doesn't look like all of them are used directly but some are instead used through `@seadub/danger-plugin-dependencies` and `node-appc` and others.

I've tried fixing some of them by running `npm audit fix` but there are some dependencies like `xmldom` that are going to require manual intervention.

I know it is a lot of work to update dependencies but I would highly recommend doing this to reduce the risk to this and other Titanium packages.

**Comment by brentonhouse** [comment]
https://github.com/advisories/GHSA-q674-xm3x-2926

**Comment by brentonhouse** [comment]
xmldom  *
Severity: moderate
Misinterpretation of malicious XML input - https://github.com/advisories/GHSA-h6q6-9hqw-rwfv
Misinterpretation of malicious XML input - https://github.com/advisories/GHSA-5fg8-2547-mr8q

**Comment by ewanharris** [comment]
We'll look to fix these in due time, but it should be stated that:

* Development dependencies (danger and @seadub/danger-plugin-dependencies) are not included in the published package so those shouldn't be a concern to end users
* The threat model for a build tool like Titanium that mostly works where the input provided by a user is known (i.e the application project) is vastly different to a server threat model that takes untrusted user input (as you can see with the blogposts for the xmldom issues)

**Comment by brentonhouse** [comment]
Awesome!  Thanks @ewanharris !
