### ISSUE TITLE
Assets folder doesn't work for CommonJS modules

### ISSUE THREAD

**Issue by DrMoriarty** [appcelerator/titanium#65]
Hello! 
There is my question on the forum http://developer.appcelerator.com/question/158947/localization-in-commonjs-module-for-ios

I'm developing a CommonJS module and I want to add localization files in it. I've successfully added localization files for android, but not for iOS. 
The common way using assets folder works for iOS native modules, but it doesn't work for CommonJS modules.

As far as I see, titanium ignores assets folder in CommonJS modules.

**Comment by skypanther** [comment]
Given that this issue is over a year old, I'm going to close it. If it's still a problem, would you open a [Jira ticket](https://jira.appcelerator.org)?
